version: 0.2

phases:
  install:
    runtime-versions:
        dotnet: 2.2
pre_build:
  ommands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-west-2 --no-include-email)
      - REPOSITORY_URI=320004554292.dkr.ecr.us-west-2.amazonaws.com/testgitapp
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
build:
  commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t testgitapp:$IMAGE_TAG .
      - docker tag testgitapp:$IMAGE_TAG $REPOSITORY_URI:testgitapp.$IMAGE_TAG
post_build:
  commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:testgitapp.$IMAGE_TAG
      - printf '[{"name":"testapp","imageUri":"%s"}]' $REPOSITORY_URI:testgitapp.$IMAGE_TAG > $CODEBUILD_SRC_DIR/imagedefinitions.json
artifacts:
   files:
      - $CODEBUILD_SRC_DIR/imagedefinitions.json
